### ISSUE TITLE
import tensorflow fails. Is downgrading an option?

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/tutorial-tf-pipeline#2]
**Rasa Core version**: 0.9.3

**Python version**:  Python 3.6.5 :: Anaconda, Inc.

**Operating system** Ubuntu 16.04.4 LTS

**Issue**:
When I try to import tensorflow I get the error
`Illegal instruction (core dumped)`
A [common issue](https://github.com/tensorflow/tensorflow/issues/17411) with tensorflow 1.6 and above, is (apparently) missing support for AVX on some CPUs. 
rasa_core requires tensorflow 1.8, but I am able to run tutorial-tf-pipeline with tensorflow 1.5.
Should I expect problems when working in an older version of tensorflow?

**Comment by sneel0428** [comment]
I am also very curious about that, as I am having the same issue. Same as you, I reinstalled tensorflow specifying v.1.5 and training seems to work correctly, but I am curious as to the official reason. 

Out of curiosity are you using a virtualenv?

**Comment by Krogsager** [comment]
@sneel0428 
Yes I've created an environment with conda. However I did not take special care to use `conda install`, I just did `pip install`

**Comment by JustinaPetr** [comment]
Hey @Krogsager, apologies for taking so long to respond. Yeah, tensorflow tends to be stubborn sometimes. You should be able to use tensorflow 1.5 without any visible limitations for Rasa Core
