### ISSUE TITLE
python -m rasa_core.run error

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/tutorial-tf-pipeline#3]
I have got an error when running command below:
```console
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu_model
```

```python
raise CoreError(u"Unable to load any data from source yaml file")
pykwalify.errors.CoreError: <CoreError: error code 3: Unable to load any data from source yaml file: Path: '/'>
```

**Comment by JustinaPetr** [comment]
Hey, Reza. What versions of Rasa NLU and Rasa Core were you using?

**Comment by reza-ebrahimi** [comment]
@JustinaPetr Hello Justina! I'm using master branch for both rasa_nlu and rasa_core.

**Comment by coltearobert** [comment]
Did you figured out how to fix it ? I have the same problem :(

**Comment by reza-ebrahimi** [comment]
I think this and such errors like this related to rasa_core and rasa_nlu dependencies, if you've install both on a system they will override dependencies based on installation order. 

I suggest you to install with order below, but note that I'm not trying it for this case:
1) install rasa_nlu dependencies
2) install rasa_core dependencies
3) install rasa_core
4) install rasa_nlu

**Comment by JustinaPetr** [comment]
I am not able to reproduce it even on a fresh server. The error itself suggests that there are issues reading in the yml file. Any chance you made some changes to domain file?

**Comment by reza-ebrahimi** [comment]
@JustinaPetr I've tested with our new image and doesn't see any error, I'm going to close this issue.

But I've cloning this repository today and testing it, the result is posted below:

```console
root@7c551bdf2506:/chatbot# ./entrypoint.sh run
Using TensorFlow backend.
2018-07-23 12:39:01 WARNING  py.warnings  - /usr/local/lib/python3.5/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Bot loaded. Type a message and press enter: 
Hello
chatbot> Bye!
I am new to Berlin and I would like to join some meetups. Any suggestions?
chatbot> Talk to you later!
Sure! Can you also tell me how can I get to the venue?
chatbot> Have a great day!
Thanks a lot. Talk to you later.
chatbot> Bye!
```

So I'm wondering why results is different than the flow posted in README file!

**Comment by mjspeck** [comment]
I don't get any error, but I get the warning that is posted above. Is there an issue for that warning being tracked? I currently have `rasa-core 0.12.3`, `rasa-core-sdk 0.12.1`, and `rasa-nlu 0.13.8`.

**Comment by i-am-dejan** [comment]
The warning also occurs to me. I've ignored it so far, but it would be nicer if the message didn't appear anymore. 

```
dejan@testserver:~/chatbot$ pip list | grep rasa
rasa-core                          0.12.3
rasa-core-sdk                      0.12.2
rasa-nlu                           0.13.8
```
